services:
  app:
    platform: linux/amd64
    build:
      context: ..                
      dockerfile: infra/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - CUDA_VISIBLE_DEVICES=
    volumes:
      - "..:/workspace"
    working_dir: /workspace 
